#!/usr/bin/env python3
"""Freeze deterministic S100 Nash-e calibration and A/B fixtures.

The generated tree is build-only data.  It never opens a device or a control
transport.  Source model hashes are checked against the completed X5 static
audit before any file is copied into the OpenExplorer workspace.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime
from pathlib import Path

import numpy as np
import onnx
import onnxruntime as ort

from s100_semantic_fixtures import semantic_samples


CALIBRATION_COUNT = 64
TEST_COUNT = 128
CALIBRATION_SEED = 2026082901
TEST_SEED = 2026082902
AUDIT_REWRITE_MAX_ABS = 1e-4

# The official RL policies are unusually sensitive to weight quantization.
# D3 attempt 2 proved that the base locomotion policy clears every frozen gate
# in INT16, while the other policies and encoder require FP16 to retain the
# action/feature contract.  This is a BPU precision choice, not a relaxed gate.
BPU_PRECISION = {
    "encoder": "float16",
    "policy": "int16",
    "policy_amp": "float16",
    "policy_attn_enc": "float16",
    "policy_dance0": "float16",
    "policy_dance1": "float16",
    "policy_getup": "float16",
    "policy_interrupt": "float16",
    "policy_parkour": "float16",
    "policy_wave": "float16",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def rewrite_parkour_einsum(source: Path, destination: Path) -> dict[str, object]:
    """Replace the single unsupported be,beo->bo Einsum with exact primitives."""

    model = onnx.load(str(source), load_external_data=True)
    rewritten = []
    replacements = 0
    for node in model.graph.node:
        equation = None
        if node.op_type == "Einsum":
            for attribute in node.attribute:
                if attribute.name == "equation":
                    equation = onnx.helper.get_attribute_value(attribute)
                    if isinstance(equation, bytes):
                        equation = equation.decode("utf-8")
        if node.op_type != "Einsum" or equation != "be,beo->bo":
            rewritten.append(node)
            continue
        if len(node.input) != 2 or len(node.output) != 1:
            raise RuntimeError("unexpected parkour Einsum arity")
        prefix = (node.name or "parkour_einsum").strip("/").replace("/", "_")
        lhs = f"{prefix}_lhs_unsqueezed"
        product = f"{prefix}_product"
        rewritten.extend(
            [
                onnx.helper.make_node(
                    "Unsqueeze", [node.input[0]], [lhs], name=f"{prefix}_Unsqueeze", axes=[2]
                ),
                onnx.helper.make_node(
                    "Mul", [lhs, node.input[1]], [product], name=f"{prefix}_Mul"
                ),
                onnx.helper.make_node(
                    "ReduceSum",
                    [product],
                    [node.output[0]],
                    name=f"{prefix}_ReduceSum",
                    axes=[1],
                    keepdims=0,
                ),
            ]
        )
        replacements += 1
    if replacements != 1:
        raise RuntimeError(f"expected one parkour Einsum replacement, got {replacements}")
    del model.graph.node[:]
    model.graph.node.extend(rewritten)
    model.doc_string = (
        (model.doc_string + "\n") if model.doc_string else ""
    ) + "S100 audit rewrite: Einsum be,beo->bo = ReduceSum(Unsqueeze(lhs)*rhs, axis=1)."
    onnx.checker.check_model(model)
    onnx.save(model, str(destination))
    return {
        "name": "einsum_be_beo_to_bo",
        "source_operator": "Einsum equation=be,beo->bo",
        "replacement": "Unsqueeze(axis=2) -> Mul -> ReduceSum(axis=1, keepdims=0)",
        "replacement_count": replacements,
    }


def yaml_text(
    model_name: str,
    compile_onnx_name: str,
    input_name: str,
    input_shape: tuple[int, ...],
    precision: str,
) -> str:
    shape_text = "x".join(str(value) for value in input_shape)
    return f"""# Generated by prepare_s100_bpu_assets.py; frozen for D3.
model_parameters:
  onnx_model: '../models/{compile_onnx_name}'
  march: 'nash-e'
  layer_out_dump: false
  working_dir: '../compiled/{model_name}'
  output_model_file_prefix: '{model_name}_nashe'

input_parameters:
  input_name: '{input_name}'
  input_type_rt: 'featuremap'
  input_type_train: 'featuremap'
  input_shape: '{shape_text}'
  norm_type: 'no_preprocess'

calibration_parameters:
  cal_data_dir: '../calibration/{model_name}'
  cal_data_type: 'float32'
  calibration_type: 'max'
  optimization: 'set_all_nodes_{precision}'
  max_percentile: 0.9999

compiler_parameters:
  jobs: 4
  compile_mode: 'latency'
  debug: true
  optimize_level: 'O2'
  extra_params:
    input_no_padding: true
    output_no_padding: true
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    repo = args.repo.resolve()
    output = (args.output or repo / "build" / "s100_bpu").resolve()
    contract_path = repo / "evidence" / "b0" / "onnx_contract.json"
    upstream = repo / "upstream" / "roboparty_deploy"
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    if contract.get("result") != "PASS":
        raise RuntimeError("X5 ONNX contract is not PASS")

    for name in ("models", "configs", "calibration", "test", "host_reference", "compiled", "logs"):
        (output / name).mkdir(parents=True, exist_ok=True)

    encoder_source = upstream / "src" / "camera" / "models" / "encoder.onnx"
    encoder_session = ort.InferenceSession(
        str(encoder_source), providers=["CPUExecutionProvider"]
    )

    manifest_models: list[dict[str, object]] = []
    for index, (filename, metadata) in enumerate(sorted(contract["models"].items())):
        model_name = filename.removesuffix(".onnx")
        source = upstream / metadata["relative_path"]
        expected_hash = metadata["sha256"]
        observed_hash = sha256(source)
        if observed_hash != expected_hash:
            raise RuntimeError(f"source hash mismatch for {source}: {observed_hash}")

        model = onnx.load(str(source), load_external_data=True)
        onnx.checker.check_model(model)
        input_meta = metadata["inputs"][0]
        output_meta = metadata["outputs"][0]
        input_shape = tuple(int(value) for value in input_meta["shape"])
        copied_model = output / "models" / filename
        shutil.copy2(source, copied_model)
        if sha256(copied_model) != expected_hash:
            raise RuntimeError(f"copied model hash mismatch for {filename}")

        calibration, calibration_provenance = semantic_samples(
            model_name,
            CALIBRATION_COUNT,
            CALIBRATION_SEED + index,
            upstream,
            encoder_session,
        )
        tests, test_provenance = semantic_samples(
            model_name,
            TEST_COUNT,
            TEST_SEED + index,
            upstream,
            encoder_session,
        )
        expected_sample_shape = (CALIBRATION_COUNT, *input_shape[1:])
        if calibration.shape != expected_sample_shape:
            raise RuntimeError(
                f"calibration shape mismatch for {model_name}: "
                f"{calibration.shape} != {expected_sample_shape}"
            )
        expected_test_shape = (TEST_COUNT, *input_shape[1:])
        if tests.shape != expected_test_shape:
            raise RuntimeError(
                f"test shape mismatch for {model_name}: {tests.shape} != {expected_test_shape}"
            )
        calibration_dir = output / "calibration" / model_name
        test_dir = output / "test" / model_name
        calibration_dir.mkdir(parents=True, exist_ok=True)
        test_dir.mkdir(parents=True, exist_ok=True)
        for old in calibration_dir.glob("*.npy"):
            old.unlink()
        for sample_index, sample in enumerate(calibration):
            np.save(calibration_dir / f"cal_{sample_index:03d}.npy", sample[None])
        test_path = test_dir / "inputs.npy"
        np.save(test_path, tests.reshape((TEST_COUNT, *input_shape[1:])))

        session = ort.InferenceSession(str(source), providers=["CPUExecutionProvider"])
        input_name = session.get_inputs()[0].name
        output_name = session.get_outputs()[0].name
        references = np.concatenate(
            [session.run([output_name], {input_name: sample[None]})[0] for sample in tests],
            axis=0,
        ).astype(np.float32, copy=False)
        reference_path = output / "host_reference" / f"{model_name}.npy"
        np.save(reference_path, references)

        compile_model = copied_model
        transform = None
        equivalence_max_abs = 0.0
        if model_name == "policy_parkour":
            compile_model = output / "models" / "policy_parkour_bpu.onnx"
            transform = rewrite_parkour_einsum(source, compile_model)
            rewritten_session = ort.InferenceSession(
                str(compile_model), providers=["CPUExecutionProvider"]
            )
            rewritten_outputs = np.concatenate(
                [
                    rewritten_session.run(
                        [rewritten_session.get_outputs()[0].name],
                        {rewritten_session.get_inputs()[0].name: sample[None]},
                    )[0]
                    for sample in tests
                ],
                axis=0,
            )
            equivalence_max_abs = float(np.max(np.abs(rewritten_outputs - references)))
            if equivalence_max_abs > AUDIT_REWRITE_MAX_ABS:
                raise RuntimeError(
                    f"parkour audit rewrite is not equivalent: max_abs={equivalence_max_abs}"
                )

        config_path = output / "configs" / f"{model_name}_nashe.yaml"
        precision = BPU_PRECISION[model_name]
        config_path.write_text(
            yaml_text(model_name, compile_model.name, input_name, input_shape, precision),
            encoding="utf-8",
            newline="\n",
        )
        manifest_models.append(
            {
                "name": model_name,
                "source_relative_path": metadata["relative_path"],
                "onnx_sha256": expected_hash,
                "compile_onnx_file": f"models/{compile_model.name}",
                "compile_onnx_sha256": sha256(compile_model),
                "audit_transform": transform,
                "audit_transform_host_equivalence_max_abs": equivalence_max_abs,
                "input_name": input_name,
                "input_shape": list(input_shape),
                "output_name": output_name,
                "output_shape": output_meta["shape"],
                "calibration_count": CALIBRATION_COUNT,
                "calibration_seed": CALIBRATION_SEED + index,
                "calibration_provenance": calibration_provenance,
                "test_count": TEST_COUNT,
                "test_seed": TEST_SEED + index,
                "test_provenance": test_provenance,
                "test_input_sha256": sha256(test_path),
                "host_reference_sha256": sha256(reference_path),
                "config_sha256": sha256(config_path),
                "target_march": "nash-e",
                "input_type": "featuremap_float32",
                "bpu_precision": precision,
                "quantization": (
                    "PTQ max, set_all_nodes_int16"
                    if precision == "int16"
                    else "accuracy-preserving set_all_nodes_float16; compiler may partition unsupported activations"
                ),
            }
        )

    manifest = {
        "schema_version": 1,
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "scope": "S100 single-board offline BPU conversion fixtures; no device/control I/O",
        "fixture_profile": "official_contract_semantic_v2",
        "fixture_generator": {
            "prepare_script": "scripts/host/prepare_s100_bpu_assets.py",
            "prepare_script_sha256": sha256(Path(__file__).resolve()),
            "semantic_module": "scripts/host/s100_semantic_fixtures.py",
            "semantic_module_sha256": sha256(
                Path(__file__).resolve().with_name("s100_semantic_fixtures.py")
            ),
        },
        "source_contract": str(contract_path.relative_to(repo)).replace("\\", "/"),
        "source_contract_sha256": sha256(contract_path),
        "target": {"board": "RDK S100", "soc": "S100", "march": "nash-e"},
        "precision_policy": BPU_PRECISION,
        "toolchain_required": {"rdk_os": "4.0.5", "openexplorer": "3.7.0"},
        "acceptance": {
            "cosine_similarity_target": 0.999,
            "per_sample_cosine_hard_floor": 0.99,
            "policy_max_abs_error": 0.10,
            "policy_direction_threshold": 0.05,
            "policy_direction_agreement_min": 0.99,
            "policy_p99_ms_max": 20.0,
            "audit_rewrite_max_abs": AUDIT_REWRITE_MAX_ABS,
            "warmup_min": 20,
            "measurements_min": 100,
        },
        "models": manifest_models,
        "result": "ASSETS_FROZEN",
    }
    manifest_path = output / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(manifest_path)


if __name__ == "__main__":
    main()
